name: Integration Tests [Experiment]
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run-core-e2e-tests:
    runs-on: ubuntu-latest
    environment: azure-prod-peco
    env:
      DBT_DATABRICKS_HOST_NAME: ${{ secrets.DATABRICKS_HOST }}
      DBT_DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      TEST_PECO_WAREHOUSE_JDBC_URL: ${{ secrets.TEST_PECO_WAREHOUSE_JDBC_URL }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            dev-requirements.txt
      - name: Get http path from environment
        run: python .github/workflows/read_http_path.py
        shell: sh
      - name: Verify http_path was found
        run: echo $DBT_DATABRICKS_HTTP_PATH
      - name: Install dependencies
        id: install-dependencies
        run: pip install -r requirements.txt -r dev-requirements.txt
      - name: Run adapter tests
        run: DBT_DATABRICKS_HOST_NAME=$DBT_DATABRICKS_HOST_NAME DBT_DATABRICKS_HTTP_PATH=$DBT_DATABRICKS_HTTP_PATH DBT_DATABRICKS_TOKEN=$DBT_DATABRICKS_TOKEN python -m pytest -v --profile databricks_sql_endpoint tests/functional/adapter/test_basic.py::TestSimpleMaterializationsDatabricks::test_base
      # - name: Run integration tests
      #   run: DBT_DATABRICKS_HOST_NAME=$DBT_DATABRICKS_HOST_NAME DBT_DATABRICKS_HTTP_PATH=$DBT_DATABRICKS_HTTP_PATH DBT_DATABRICKS_TOKEN=$DBT_DATABRICKS_TOKEN python -m pytest -v --profile databricks_sql_endpoint tests/integration/*