name: Integration Tests
# on: workflow_dispatch
on:
  push:
    branches: [add-integration-tests]
  pull_request:
    branches: [add-integration-tests]
jobs:
  run-core-e2e-tests:
    runs-on: ubuntu-latest
    environment: azure-prod-peco
    env:
      DBT_DATABRICKS_HOST_NAME: ${{ secrets.DATABRICKS_HOST }}
      DBT_DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      TEST_PECO_WAREHOUSE_JDBC_URL: ${{ secrets.TEST_PECO_WAREHOUSE_JDBC_URL }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            dev-requirements.txt
      - name: Get http path from environment
        run: python .github/workflows/read_http_path.py
        shell: sh
      - name: Install dependencies
        id: install-dependencies
        # run: pip install -r requirements.txt -r dev-requirements.txt
        # Tox will install any requirements needed
        run: pip install tox
      - name: Run adapter tests
        run: DBT_TEST_USER=notnecessaryformosttests@example.com DBT_DATABRICKS_HOST_NAME=$DBT_DATABRICKS_HOST_NAME DBT_DATABRICKS_HTTP_PATH=$DBT_DATABRICKS_HTTP_PATH DBT_DATABRICKS_TOKEN=$DBT_DATABRICKS_TOKEN tox -e integration-databricks-sql-endpoint
